# Generated by Django 6.0.6 on 2026-07-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='updatged',
            new_name='updated',
        ),
    ]
